# Generated by Django 5.0.3 on 2024-04-01 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(blank=True, to='pybo.questiontopic'),
        ),
    ]
