# Generated by Django 5.0.3 on 2024-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_alter_question_owner_remove_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
